--- Makefile    2023-10-02 16:48:57.001338786 +0200
+++ Makefile.2       2023-10-02 16:48:41.081451959 +0200
@@ -90,7 +90,7 @@
        floatcomp.$(OBJEXT) gawkmisc.$(OBJEXT) getopt.$(OBJEXT) \
        getopt1.$(OBJEXT) io.$(OBJEXT) main.$(OBJEXT) msg.$(OBJEXT) \
        node.$(OBJEXT) random.$(OBJEXT) re.$(OBJEXT) regex.$(OBJEXT) \
-       replace.$(OBJEXT) version.$(OBJEXT)
+       replace.$(OBJEXT) version.$(OBJEXT) $(mms).$(OBJEXT)
 am_gawk_OBJECTS = $(am__objects_1) eval.$(OBJEXT) profile.$(OBJEXT)
 gawk_OBJECTS = $(am_gawk_OBJECTS)
 gawk_LDADD = $(LDADD)
